from django.urls import path
from rest_framework.routers import DefaultRouter
from .api_views import (
    RoomListCreateView,
    RoomDetailView,
    RoomMessageListCreateView,
    RoomMarkReadView,
    RoomMarkUnreadView,
    RoomCountUnreadView,
    RoomLastReadView,
    RoomReadView,
    RoomConfigView,
    MessageDetailView,
    MessageRepliesView,
    MessageReactionsView,
    RoomConfigStateView,
    MessageFlagView,
    MessagePinView,
    MessageUnpinView,
    MessageActionView,
    RoomArchiveView,
    RoomUnarchiveView,
    RoomTruncateView,
    RoomCooldownView,
    RoomMembersView,
    RoomPinnedMessagesView,
    RoomQueryView,
    ActiveRoomListView,
    RoomDraftView,
    NotificationListView,
    MutedChannelListView,
    LinkPreviewView,
    PollListCreateView,
    PollDetailView,
    PollOptionCreateView,
    RoomHideView,
    RoomShowView,
    ReactionDetailView,
    MuteStatusView,
    MessageRestoreView,
    MutedUsersView,
    MuteUserView,
    UnmuteUserView,
    AttachmentUploadView,
    ReminderListCreateView,
    ThreadListView,
    RecoverStateView,
    TextComposerView,
    ComposeView,
    EditingAuditStateView,
    CompositionIsEmptyView,
    SubarrayView,
    AxiosTestView,
    ConnectionIDView,
    WsAuthView,
)

router = DefaultRouter()
# Router is not used here but left for extensibility

urlpatterns = [
    path("api/rooms/", RoomListCreateView.as_view(), name="room-list"),
    path("api/rooms/active/", ActiveRoomListView.as_view(), name="active-rooms"),
    path("api/rooms/<str:uuid>/", RoomDetailView.as_view(), name="room-detail"),
    path(
        "api/rooms/<str:room_uuid>/messages/",
        RoomMessageListCreateView.as_view(),
        name="room-messages",
    ),
    path(
        "api/rooms/<str:room_uuid>/mark_read/",
        RoomMarkReadView.as_view(),
        name="room-mark-read",
    ),
    path(
        "api/rooms/<str:room_uuid>/mark_unread/",
        RoomMarkUnreadView.as_view(),
        name="room-mark-unread",
    ),
    path(
        "api/rooms/<str:room_uuid>/count_unread/",
        RoomCountUnreadView.as_view(),
        name="room-count-unread",
    ),
    path(
        "api/rooms/<str:room_uuid>/last_read/",
        RoomLastReadView.as_view(),
        name="room-last-read",
    ),
    path(
        "api/rooms/<str:room_uuid>/read/",
        RoomReadView.as_view(),
        name="room-read",
    ),
    path(
        "api/rooms/<str:room_uuid>/draft/",
        RoomDraftView.as_view(),
        name="room-draft",
    ),
    path(
        "api/rooms/<str:room_uuid>/config/",
        RoomConfigView.as_view(),
        name="room-config",
    ),
    path("api/rooms/<str:room_uuid>/config-state/", RoomConfigStateView.as_view(), name="room-config-state"),
    path(
        "api/rooms/<str:room_uuid>/cooldown/",
        RoomCooldownView.as_view(),
        name="room-cooldown",
    ),
    path(
        "api/rooms/<str:room_uuid>/members/",
        RoomMembersView.as_view(),
        name="room-members",
    ),
    path(
        "api/rooms/<str:room_uuid>/pinned/",
        RoomPinnedMessagesView.as_view(),
        name="room-pinned-messages",
    ),
    path(
        "api/rooms/<str:room_uuid>/query/",
        RoomQueryView.as_view(),
        name="room-query",
    ),
    path(
        "api/rooms/<str:room_uuid>/archive/",
        RoomArchiveView.as_view(),
        name="room-archive",
    ),
    path(
        "api/rooms/<str:room_uuid>/unarchive/",
        RoomUnarchiveView.as_view(),
        name="room-unarchive",
    ),
    path(
        "api/rooms/<str:room_uuid>/truncate/",
        RoomTruncateView.as_view(),
        name="room-truncate",
    ),
    path(
        "api/rooms/<str:room_uuid>/hide/",
        RoomHideView.as_view(),
        name="room-hide",
    ),
    path(
        "api/rooms/<str:room_uuid>/show/",
        RoomShowView.as_view(),
        name="room-show",
    ),
    path(
        "api/messages/<int:message_id>/",
        MessageDetailView.as_view(),
        name="message-detail",
    ),
    path(
        "api/messages/<int:message_id>/restore/",
        MessageRestoreView.as_view(),
        name="message-restore",
    ),
    path(
        "api/messages/<int:message_id>/replies/",
        MessageRepliesView.as_view(),
        name="message-replies",
    ),
    path("api/notifications/", NotificationListView.as_view(), name="notifications"),
    path("api/reminders/", ReminderListCreateView.as_view(), name="reminders"),
    path("api/threads/", ThreadListView.as_view(), name="threads"),
    path("api/muted-channels/", MutedChannelListView.as_view(), name="muted-channels"),
    path(
        "api/messages/<int:message_id>/reactions/",
        MessageReactionsView.as_view(),
        name="message-reactions",
    ),
    path("api/link-preview/", LinkPreviewView.as_view(), name="link-preview"),
    path("api/attachments/", AttachmentUploadView.as_view(), name="attachments"),
    path(
        "api/messages/<int:message_id>/flag/",
        MessageFlagView.as_view(),
        name="message-flag",
    ),
    path(
        "api/messages/<int:message_id>/pin/",
        MessagePinView.as_view(),
        name="message-pin",
    ),
    path(
        "api/messages/<int:message_id>/unpin/",
        MessageUnpinView.as_view(),
        name="message-unpin",
    ),
    path(
        "api/messages/<int:message_id>/actions/",
        MessageActionView.as_view(),
        name="message-actions",
    ),
    path(
        "api/messages/<int:message_id>/reactions/<int:reaction_id>/",
        ReactionDetailView.as_view(),
        name="reaction-detail",
    ),
    path(
        "api/polls/",
        PollListCreateView.as_view(),
        name="poll-create",
    ),
    path(
        "api/polls/<str:poll_id>/",
        PollDetailView.as_view(),
        name="poll-detail",
    ),
    path(
        "api/polls/<str:poll_id>/options/",
        PollOptionCreateView.as_view(),
        name="poll-option-create",
    ),
    path(
        "api/muted-users/",
        MutedUsersView.as_view(),
        name="muted-users",
    ),
    path(
        "api/mute-status/<str:target_username>/",
        MuteStatusView.as_view(),
        name="mute-status",
    ),
    path(
        "api/mute/<str:target_username>/",
        MuteUserView.as_view(),
        name="user-mute",
    ),
    path(
        "api/unmute/<str:target_username>/",
        UnmuteUserView.as_view(),
        name="user-unmute",
    ),
    path("api/recover-state/", RecoverStateView.as_view(), name="recover-state"),
    path("api/text-composer/", TextComposerView.as_view(), name="text-composer"),
    path("api/compose/", ComposeView.as_view(), name="compose"),
    path("api/composition-is-empty/", CompositionIsEmptyView.as_view(), name="composition-is-empty"),
    path("api/editing-audit-state/", EditingAuditStateView.as_view(), name="editing-audit-state"),
    path("api/subarray/", SubarrayView.as_view(), name="subarray"),
    path("api/test/", AxiosTestView.as_view(), name="axios-test"),
    path("api/connection-id/", ConnectionIDView.as_view(), name="connection-id"),
    path("api/ws-auth/", WsAuthView.as_view(), name="ws-auth"),
]
