# Generated by Django 4.2.1 on 2025-12-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts_supabase",
            "0002_userprofile_display_name_userprofile_extra_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="license_number",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="return_address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="signature_image",
        ),
    ]
