# Generated by Django 4.2.26 on 2025-12-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_supabase', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
