import type { Metadata } from "next";
import "./globals.css";
import 'stream-chat-react/dist/css/v2/index.css'; // ← v1 if you prefer
import { SessionProvider } from "@/lib/SessionProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
