import type { Metadata } from "next";
import '@iliad/stream-chat-shim/dist/css/v2/index.css'; // ← v1 if you prefer
import "./globals.css";

import { SessionProvider } from "@/lib/SessionProvider";
import AuthBootstrap from "./AuthBootstrap";
import EndpointConfig from "./endpoint-config";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthBootstrap />
        <EndpointConfig />
        <SessionProvider>
          {children}
        </SessionProvider>
        {/* <Providers></Providers>   */}
      </body>
    </html>
  );
}
