packages:
  - frontend
  - backend
  - libs/*
  - docs

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild

packageExtensions:
  "stream-chat-react@*":
    peerDependencies:
      react: ">=18"
