# Generated by Django 4.2.1 on 2025-06-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_add_message_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
