# Generated by Django 4.2.1 on 2025-06-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_notification"),
        ("chat", "0005_reaction"),
    ]

    operations = []
