# Generated by Django 4.2.1 on 2025-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_add_custom_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
