# Generated by Django 4.2.1 on 2025-06-16 16:20
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0007_add_custom_data'),
        ('chat', '0006_polloption'),
        ('chat', '0006_merge_0005_notification_0005_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
