# Generated by Django 4.2.1 on 2025-06-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_merge_0005_notification_0005_reaction"),
        ("chat", "0006_polloption"),
        ("chat", "0007_add_custom_data"),
    ]

    operations = []
