# Generated by Django 4.2.1 on 2025-06-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_add_room_data"),
        ("chat", "0008_flag"),
        ("chat", "0008_merge_20250616_1839"),
        ("chat", "0008_message_deleted_at"),
    ]

    operations = []
