# Generated by Django 4.2.1 on 2025-06-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_merge_20250616_1945"),
        ("chat", "0009_merge_20250616_1951"),
        ("chat", "0009_merge_20250616_1956"),
        ("chat", "0009_user_mute"),
    ]

    operations = []
