# Generated by Django 4.2.1 on 2025-06-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_merge_20250616_2245"),
        ("chat", "0010_room_mute"),
    ]

    operations = []
