# Generated by Django 4.2.1 on 2025-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_poll"),
        ("chat", "0011_merge_room_mute"),
        ("chat", "0012_reminder"),
    ]

    operations = []
