"""Minimal URLconf for focused REST room/message authorization tests."""

from django.urls import path

from stream_server_django.chat.api_views import (
    ActiveRoomListView,
    MessageActionView,
    MessageDetailView,
    MessageFlagView,
    MessageHideView,
    MessagePinView,
    MessageReactionTypeView,
    MessageRestoreView,
    MessageUnpinView,
    MutedChannelListView,
    RoomArchiveView,
    RoomConfigStateView,
    RoomConfigView,
    RoomCooldownView,
    RoomDetailView,
    RoomDraftView,
    RoomHideView,
    RoomLastReadView,
    RoomListCreateView,
    RoomMarkReadView,
    RoomMarkUnreadView,
    RoomMemberMuteCreateView,
    RoomMembersCIDView,
    RoomMembersView,
    RoomMessageDetailView,
    RoomMessageListCreateView,
    RoomMuteStatusView,
    RoomPinnedMessagesView,
    RoomQueryView,
    RoomReadView,
    RoomShowView,
    RoomTruncateView,
    RoomUnarchiveView,
    RoomCountUnreadView,
    SearchMessagesView,
)
from stream_server_django.drafts.views import RoomDraftView as LightweightDraftView
from stream_server_django.rooms import views as room_views
from stream_server_django.rooms.views_config import (
    RoomConfigStateView as LightweightConfigStateView,
)
from stream_server_django.chat.views_threads import MessageRepliesView, ThreadListView


urlpatterns = [
    path("light/rooms/", room_views.list_rooms),
    path("light/rooms/active/", room_views.list_active_rooms),
    path("light/rooms/<path:cid>/members/", room_views.list_room_members_cid),
    path("light/rooms/<str:room_uuid>/messages/", room_views.room_messages),
    path("light/rooms/<str:room_uuid>/draft/", LightweightDraftView.as_view()),
    path(
        "light/rooms/<str:room_uuid>/config-state/",
        LightweightConfigStateView.as_view(),
    ),
    path("search/messages/", SearchMessagesView.as_view(), name="auth-search"),
    path("api/rooms/", RoomListCreateView.as_view(), name="auth-room-list"),
    path("api/rooms/active/", ActiveRoomListView.as_view(), name="auth-active-rooms"),
    path(
        "api/rooms/<str:uuid>/",
        RoomDetailView.as_view(),
        name="auth-room-detail",
    ),
    path(
        "api/rooms/<path:cid>/messages/<str:message_id>/",
        RoomMessageDetailView.as_view(),
        name="auth-room-message-detail",
    ),
    path(
        "api/rooms/<path:cid>/messages/",
        RoomMessageListCreateView.as_view(),
        name="auth-room-messages",
    ),
    path(
        "test/rooms/<str:room_uuid>/members/",
        RoomMembersView.as_view(),
        name="auth-room-members",
    ),
    path(
        "test/cids/<path:cid>/members/",
        RoomMembersCIDView.as_view(),
        name="auth-room-members-cid",
    ),
    path("test/rooms/<str:room_uuid>/mark-read/", RoomMarkReadView.as_view()),
    path("test/rooms/<str:room_uuid>/mark-unread/", RoomMarkUnreadView.as_view()),
    path("test/rooms/<str:room_uuid>/count-unread/", RoomCountUnreadView.as_view()),
    path("test/rooms/<str:room_uuid>/last-read/", RoomLastReadView.as_view()),
    path("test/rooms/<str:room_uuid>/read/", RoomReadView.as_view()),
    path("test/rooms/<str:room_uuid>/draft/", RoomDraftView.as_view()),
    path("test/rooms/<path:cid>/config/", RoomConfigView.as_view()),
    path("test/rooms/<str:room_uuid>/config-state/", RoomConfigStateView.as_view()),
    path("test/rooms/<str:room_uuid>/cooldown/", RoomCooldownView.as_view()),
    path("test/rooms/<path:cid>/mutes/", RoomMemberMuteCreateView.as_view()),
    path("test/rooms/<path:cid>/mute/", RoomMuteStatusView.as_view()),
    path("test/muted-channels/", MutedChannelListView.as_view()),
    path("test/rooms/<str:room_uuid>/pinned/", RoomPinnedMessagesView.as_view()),
    path("test/rooms/<str:room_uuid>/query/", RoomQueryView.as_view()),
    path("test/rooms/<str:room_uuid>/archive/", RoomArchiveView.as_view()),
    path("test/rooms/<str:room_uuid>/unarchive/", RoomUnarchiveView.as_view()),
    path("test/rooms/<str:room_uuid>/truncate/", RoomTruncateView.as_view()),
    path("test/rooms/<str:room_uuid>/hide/", RoomHideView.as_view()),
    path("test/rooms/<str:room_uuid>/show/", RoomShowView.as_view()),
    path("api/messages/<str:message_id>/", MessageDetailView.as_view()),
    path("api/messages/<str:message_id>/hide/", MessageHideView.as_view()),
    path("api/messages/<str:message_id>/restore/", MessageRestoreView.as_view()),
    path(
        "api/messages/<str:message_id>/reactions/<str:reaction_type>/",
        MessageReactionTypeView.as_view(),
    ),
    path("api/messages/<str:message_id>/flag/", MessageFlagView.as_view()),
    path("api/messages/<str:message_id>/pin/", MessagePinView.as_view()),
    path("api/messages/<str:message_id>/unpin/", MessageUnpinView.as_view()),
    path("api/messages/<str:message_id>/actions/", MessageActionView.as_view()),
    path("messages/<str:message_id>/replies/", MessageRepliesView.as_view()),
    path("threads/", ThreadListView.as_view()),
]
