# Generated by Django 5.2.1 on 2025-12-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentrun_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
