# Generated by Django 5.2.1 on 2025-12-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentrun_handoff_fields'),
        ('agent', '0003_alter_documentchunk_id'),
    ]

    operations = [
    ]
