# Generated by Django 4.2.1 on 2025-10-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stream_server_django.chat", "0009_pollvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="show_in_channel",
            field=models.BooleanField(default=False),
        ),
    ]
