# Generated by Django 4.2.1 on 2025-10-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream_server_django.chat", "0013_message_hidden_message_hidden_at_message_hidden_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="active_agent_run_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="agent_busy",
            field=models.BooleanField(default=False),
        ),
    ]
