# Generated by Django 5.1.5 on 2025-04-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Stored user signature image.', null=True, upload_to='signatures/'),
        ),
    ]
