# Generated by Django 4.2.1 on 2025-10-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_addons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("ok", "Ok"),
                    ("capped", "Capped"),
                    ("handoff", "Handoff"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=16,
            ),
        ),
    ]
