"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_HIGHLIGHT_DURATION = exports.DEFAULT_UPLOAD_SIZE_LIMIT_BYTES = exports.DEFAULT_LOAD_PAGE_SCROLL_THRESHOLD = exports.DEFAULT_THREAD_PAGE_SIZE = exports.DEFAULT_JUMP_TO_PAGE_SIZE = exports.DEFAULT_NEXT_CHANNEL_PAGE_SIZE = exports.DEFAULT_INITIAL_CHANNEL_PAGE_SIZE = void 0;
exports.DEFAULT_INITIAL_CHANNEL_PAGE_SIZE = 25;
exports.DEFAULT_NEXT_CHANNEL_PAGE_SIZE = 100;
exports.DEFAULT_JUMP_TO_PAGE_SIZE = 100;
exports.DEFAULT_THREAD_PAGE_SIZE = 50;
exports.DEFAULT_LOAD_PAGE_SCROLL_THRESHOLD = 250;
exports.DEFAULT_UPLOAD_SIZE_LIMIT_BYTES = 100 * 1024 * 1024; // 100 MB
exports.DEFAULT_HIGHLIGHT_DURATION = 500;
