# Generated by Django 4.2.26 on 2025-12-09 20:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRoomPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255, unique=True)),
                ('agent_enabled', models.BooleanField(default=False)),
                ('enabled_skills', models.JSONField(default=list)),
                ('tool_hop_cap', models.PositiveIntegerField(default=2)),
                ('turn_cap', models.PositiveIntegerField(default=6)),
                ('auto_reply_mode', models.CharField(choices=[('receptionist', 'Receptionist'), ('off', 'Off'), ('manual', 'Manual')], default='receptionist', max_length=16)),
                ('handoff_message', models.CharField(default='Let me connect you with a teammate.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent room policy',
                'verbose_name_plural': 'Agent room policies',
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=255, unique=True)),
                ('cid', models.CharField(max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('tools_used', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Ok'), ('capped', 'Capped'), ('handoff', 'Handoff'), ('error', 'Error'), ('cancelled', 'Cancelled')], max_length=16)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GatingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='default', max_length=64, unique=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('min_length', models.PositiveIntegerField(default=1)),
                ('max_length', models.PositiveIntegerField(default=1000)),
                ('min_interval_seconds', models.PositiveIntegerField(default=5)),
                ('blocklist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gating configuration',
                'verbose_name_plural': 'Gating configurations',
            },
        ),
        migrations.CreateModel(
            name='SmsRoomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('phone_e164', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_e164'], name='chat_addons_phone_e_e65994_idx')],
                'unique_together': {('cid', 'phone_e164')},
            },
        ),
        migrations.CreateModel(
            name='SmsRelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('external_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=16)),
                ('message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['external_id', 'direction'], name='chat_addons_externa_cce8c6_idx')],
                'unique_together': {('direction', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='RoomOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='chat.room')),
            ],
            options={
                'verbose_name': 'Room ownership',
                'verbose_name_plural': 'Room ownership',
            },
        ),
        migrations.CreateModel(
            name='RoomAgentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_flag', to='chat.room')),
            ],
            options={
                'verbose_name': 'Agent room flag',
                'verbose_name_plural': 'Agent room flags',
            },
        ),
        migrations.CreateModel(
            name='OnCallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_oncall_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'On-call configuration',
                'verbose_name_plural': 'On-call configuration',
            },
        ),
        migrations.CreateModel(
            name='MessageProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('human', 'Human'), ('system', 'System')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='chat.message')),
            ],
            options={
                'verbose_name': 'Message provenance',
                'verbose_name_plural': 'Message provenance',
            },
        ),
        migrations.CreateModel(
            name='MessageIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('muted', models.BooleanField(default=False)),
                ('initial_broadcast', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='chat.message')),
            ],
            options={
                'verbose_name': 'Message intake',
                'verbose_name_plural': 'Message intakes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('cid', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('claim', 'Claim'), ('approve', 'Approve intake'), ('reject', 'Reject intake'), ('escalate', 'Escalate'), ('agent_enable', 'Enable agent'), ('agent_disable', 'Disable agent'), ('agent_invoke', 'Invoke agent'), ('sms_send', 'Send SMS')], max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Audit trail entry',
                'verbose_name_plural': 'Audit trail entries',
                'ordering': ('-ts', '-id'),
                'indexes': [models.Index(fields=['-ts', '-id'], name='chat_addons_ts_d3748a_idx'), models.Index(fields=['action'], name='chat_addons_action_3103a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('system', 'System')], max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent memory entry',
                'verbose_name_plural': 'Agent memory entries',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['cid', '-id'], name='agent_memory_cid_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='EscalationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('delivered_via', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('none', 'None')], default='none', max_length=8)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_escalations', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='chat.notification')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['cid', 'created_at'], name='chat_addons_cid_0f1330_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen_at'], name='chat_addons_last_se_56d70a_idx')],
            },
        ),
    ]
