# Generated by Django 4.2.26 on 2025-12-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_addons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsConsent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_e164", models.CharField(db_index=True, max_length=32, unique=True)),
                ("opted_out_at", models.DateTimeField(blank=True, null=True)),
                ("opted_in_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
