# Generated by ChatGPT

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stream_server_django.chat_addons", "0003_gatingconfig_messageintake"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsRoomLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cid", models.CharField(max_length=255)),
                ("phone_e164", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "unique_together": {("cid", "phone_e164")},
                "indexes": [
                    models.Index(
                        fields=["phone_e164"], name="chat_addons_phone_e_e65994_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SmsRelay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cid", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=8,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("direction", "external_id")},
                "indexes": [
                    models.Index(
                        fields=["external_id", "direction"],
                        name="chat_addons_externa_cce8c6_idx",
                    ),
                ],
            },
        ),
    ]
