# Generated by ChatGPT

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stream_server_django.chat_addons", "0005_notifications_models"),
        ("stream_server_django.chat", "0013_message_hidden_message_hidden_at_message_hidden_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("human", "Human"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message provenance",
                "verbose_name_plural": "Message provenance",
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.CharField(max_length=255)),
                ("cid", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("claim", "Claim"),
                            ("approve", "Approve intake"),
                            ("reject", "Reject intake"),
                            ("escalate", "Escalate"),
                            ("agent_enable", "Enable agent"),
                            ("agent_disable", "Disable agent"),
                            ("agent_invoke", "Invoke agent"),
                            ("sms_send", "Send SMS"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=255, null=True)),
                ("request_id", models.CharField(max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-ts", "-id"),
                "verbose_name": "Audit trail entry",
                "verbose_name_plural": "Audit trail entries",
            },
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(fields=["-ts", "-id"], name="chat_addons_ts_id_c1d1ba_idx"),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(fields=["action"], name="chat_addons_action_01a4a5_idx"),
        ),
    ]
