# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream_server_django.chat_addons", "0006_common_audit_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRoomPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=255, unique=True)),
                ("agent_enabled", models.BooleanField(default=False)),
                ("enabled_skills", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Agent room policy",
                "verbose_name_plural": "Agent room policies",
            },
        ),
    ]
