# Generated by Django 4.2.1 on 2025-11-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_server_django.chat_addons', '0009_agent_memory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminpresence',
            new_name='chat_addons_last_se_56d70a_idx',
            old_name='chat_addons_last_154576_idx',
        ),
        migrations.RenameIndex(
            model_name='audittrail',
            new_name='chat_addons_ts_d3748a_idx',
            old_name='chat_addons_ts_id_c1d1ba_idx',
        ),
        migrations.RenameIndex(
            model_name='audittrail',
            new_name='chat_addons_action_3103a5_idx',
            old_name='chat_addons_action_01a4a5_idx',
        ),
        migrations.RenameIndex(
            model_name='escalationrecord',
            new_name='chat_addons_cid_0f1330_idx',
            old_name='chat_addons_cid_crea_c94db4_idx',
        ),
        migrations.AlterField(
            model_name='gatingconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messageintake',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
