# Generated by Django 4.2.26 on 2025-12-01 04:11

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('chat_addons', '0011_seed_agent_lab_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=8)),
                ('topic', models.CharField(db_index=True, help_text="Short slug for the pillar/topic, e.g. 'noc_compliance', 'lien_waiver'.", max_length=128)),
                ('doc_name', models.CharField(help_text="Source document name, e.g. 'florida_noc_compliance.md'.", max_length=256)),
                ('chunk_index', models.PositiveIntegerField(help_text='Zero-based index for this chunk within its document.')),
                ('heading', models.TextField(blank=True, help_text='Section heading(s) associated with this chunk.')),
                ('text', models.TextField(help_text='The full text of this chunk that will be retrieved & shown to the LLM.')),
                ('tokens_estimated', models.PositiveIntegerField(blank=True, help_text='Approximate token count for this chunk (heuristic).', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional extra metadata (statute refs, phase, etc.).', null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['stream_server_django.state', 'topic'], name='chat_addons_state_936cc2_idx')],
                'unique_together': {('state', 'doc_name', 'chunk_index')},
            },
        ),
    ]
