"""
Django settings for jatte project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

from .security_settings import required_csv, required_secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# Production never uses development defaults: configuration errors should stop
# startup before Django serves a request.
SECRET_KEY = required_secret("DJANGO_SECRET_KEY")
SUPABASE_JWT_SECRET = required_secret("SUPABASE_JWT_SECRET")
SUPABASE_URL = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
SUPABASE_JWKS_URL = (
    f"{SUPABASE_URL.rstrip('/')}/auth/v1/keys" if SUPABASE_URL else None
)
SMS_PROVIDER = os.environ.get("SMS_PROVIDER", "adapter_http")
SMS_PROVIDER_BASE_URL = os.environ.get("SMS_PROVIDER_BASE_URL", "")
SMS_PROVIDER_TOKEN = os.environ.get("SMS_PROVIDER_TOKEN", "")
OPENPHONE_API_KEY = os.environ.get("OPENPHONE_API_KEY", "")
OPENPHONE_FROM_PHONE_ID = os.environ.get("OPENPHONE_FROM_PHONE_ID", "")
OPENPHONE_BASE_URL = os.environ.get("OPENPHONE_BASE_URL", "https://api.openphone.com")
CHAT_INTERNAL_SERVICE_TOKEN = required_secret("CHAT_INTERNAL_SERVICE_TOKEN")
CHAT_INTERNAL_SERVICE_USERNAME = os.environ.get(
    "CHAT_INTERNAL_SERVICE_USERNAME", "__chat_internal_service__"
)
SMS_WEBHOOK_SECRET = required_secret("SMS_WEBHOOK_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = required_csv("DJANGO_ALLOWED_HOSTS")
CORS_ALLOWED_ORIGINS = required_csv("DJANGO_CORS_ALLOWED_ORIGINS")
CORS_ALLOW_CREDENTIALS = False
DJANGO_WS_ALLOWED_ORIGINS = required_csv("DJANGO_WS_ALLOWED_ORIGINS")

# Attachments are private by default.  Setting the public-download flag to a
# deliberate truthy value makes each returned storage URL a bearer credential;
# see backend/SECURITY.md before enabling it.
CHAT_ATTACHMENTS_BUCKET = os.environ.get("CHAT_ATTACHMENTS_BUCKET")
CHAT_ATTACHMENTS_SERVICE_ACCOUNT_INFO = os.environ.get(
    "CHAT_ATTACHMENTS_SERVICE_ACCOUNT_JSON"
)
CHAT_ATTACHMENTS_ALLOWED_TYPES = [
    item.strip()
    for item in os.environ.get("CHAT_ATTACHMENTS_ALLOWED_TYPES", "").split(",")
    if item.strip()
]
CHAT_ATTACHMENTS_MAX_SIZE = int(
    os.environ.get("CHAT_ATTACHMENTS_MAX_SIZE", "26214400")
)
CHAT_ATTACHMENTS_UPLOAD_TTL_SECONDS = int(
    os.environ.get("CHAT_ATTACHMENTS_UPLOAD_TTL_SECONDS", "600")
)
CHAT_ATTACHMENTS_SIGN_TTL_SECONDS = int(
    os.environ.get("CHAT_ATTACHMENTS_SIGN_TTL_SECONDS", "600")
)
CHAT_ATTACHMENTS_DOWNLOAD_TTL_SECONDS = int(
    os.environ.get("CHAT_ATTACHMENTS_DOWNLOAD_TTL_SECONDS", "120")
)
CHAT_ATTACHMENTS_PUBLIC_DOWNLOADS = os.environ.get(
    "CHAT_ATTACHMENTS_PUBLIC_DOWNLOADS", "false"
).strip().lower() in {"1", "true", "yes", "on"}
CHAT_ATTACHMENTS_PUBLIC_BASE_URL = os.environ.get(
    "CHAT_ATTACHMENTS_PUBLIC_BASE_URL"
)

# The reverse proxy terminates TLS and forwards the original scheme. This makes
# request.is_secure() reliable for the legacy websocket URL compatibility API.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

AUTH_USER_MODEL = 'stream_server_django.accounts_supabase.CustomUser'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Which DRF authentication class to use for chat APIs.
# Default is Jatte's own Supabase JWT auth.
STREAM_SERVER_CHAT_AUTHENTICATION_CLASS = (
    "stream_server_django.accounts_supabase.authentication.SupabaseJWTAuthentication"
)

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

# Application definition

INSTALLED_APPS = [
    'daphne',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'stream_server_django.accounts',
    'stream_server_django.chat',
    'stream_server_django.drafts',
    'stream_server_django.core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jatte.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jatte.wsgi.application'
ASGI_APPLICATION = 'jatte.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'jatte',
        'USERNAME': 'jatte',
        'PASSWORD': 'jatte',
        'HOST': 'localhost',
        'PORT': ''
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
