#backend/jatte/settings.py

"""
Django settings for jatte project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv
import dj_database_url


OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

BASE_DIR = Path(__file__).resolve().parent.parent  # this is already there
print(BASE_DIR)
#load_dotenv(BASE_DIR.parent / ".env")  # adjust path if your .env lives elsewhere
load_dotenv(BASE_DIR / ".env")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent.parent
#BASE_DIR = Path(__file__).resolve().parent.parent  # only two parents


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%v$gh67imza=0$i%pky!jxpk*@%t+x-w$lw5lmwbvj)+#p=r#g'

# Secret key used by Supabase to sign JWTs
SUPABASE_JWT_SECRET = os.environ.get('SUPABASE_JWT_SECRET', 'changeme')
if SUPABASE_JWT_SECRET == 'changeme':
    print("[settings] WARNING: SUPABASE_JWT_SECRET not set")
elif os.environ.get("PRINT_JWT_SECRET"):
    print(
        "[settings] SUPABASE_JWT_SECRET:",
        SUPABASE_JWT_SECRET[:8] + ("..." if len(SUPABASE_JWT_SECRET) > 8 else ""),
        f"(len {len(SUPABASE_JWT_SECRET)})",
    )

# Base Supabase project URL used to fetch JWKS for verifying incoming JWTs
SUPABASE_URL = os.environ.get('NEXT_PUBLIC_SUPABASE_URL')
SUPABASE_JWKS_URL = (
    f"{SUPABASE_URL.rstrip('/')}/auth/v1/keys" if SUPABASE_URL else None
)
if os.environ.get("PRINT_JWT_SECRET"):
    print("[settings] SUPABASE_URL:", SUPABASE_URL)
    print("[settings] SUPABASE_JWKS_URL:", SUPABASE_JWKS_URL)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]

AUTH_USER_MODEL = 'accounts_supabase.CustomUser'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
# Allow REDIS_HOST to include a port via "host:port" or use a separate
# REDIS_PORT environment variable. This mirrors common Redis configuration
# strings and avoids connection errors like "localhost:6379:6379" when the
# host variable already includes the port.
REDIS_PORT = 6379
if ":" in REDIS_HOST:
    host, port = REDIS_HOST.rsplit(":", 1)
    REDIS_HOST = host
    REDIS_PORT = int(port)
else:
    REDIS_PORT = int(os.environ.get("REDIS_PORT", "6379"))


def _split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def _split_env(name: str, default: str = "") -> list[str]:
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


CHAT_ATTACHMENTS_BUCKET = os.environ.get("CHAT_ATTACHMENTS_BUCKET")
CHAT_ATTACHMENTS_SERVICE_ACCOUNT_INFO = os.environ.get(
    "CHAT_ATTACHMENTS_SERVICE_ACCOUNT_JSON"
)
CHAT_ATTACHMENTS_ALLOWED_TYPES = _split_csv(
    os.environ.get("CHAT_ATTACHMENTS_ALLOWED_TYPES", "")
)
CHAT_ATTACHMENTS_MAX_SIZE = int(os.environ.get("CHAT_ATTACHMENTS_MAX_SIZE", "26214400"))
CHAT_ATTACHMENTS_UPLOAD_TTL_SECONDS = int(
    os.environ.get("CHAT_ATTACHMENTS_UPLOAD_TTL_SECONDS", "600")
)
CHAT_ATTACHMENTS_SIGN_TTL_SECONDS = int(
    os.environ.get("CHAT_ATTACHMENTS_SIGN_TTL_SECONDS", "600")
)
CHAT_ATTACHMENTS_PUBLIC_BASE_URL = os.environ.get("CHAT_ATTACHMENTS_PUBLIC_BASE_URL")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(REDIS_HOST, REDIS_PORT)]},
    }
}

MESSAGE_BURST_RATE = os.environ.get("MESSAGE_BURST", "20/min")
MESSAGE_SUSTAINED_RATE = os.environ.get("MESSAGE_SUSTAINED", "200/hour")
REACTION_BURST_RATE = os.environ.get("REACTION_BURST", "60/min")
REACTION_SUSTAINED_RATE = os.environ.get("REACTION_SUSTAINED", "400/hour")

WS_BUCKET_CAPACITY = int(os.environ.get("WS_BUCKET_CAPACITY", "30"))
WS_BUCKET_REFILL_PER_SEC = float(os.environ.get("WS_BUCKET_REFILL_PER_SEC", "5"))
WS_RATE_LIMIT_CLOSE_CODE = int(os.environ.get("WS_RATE_LIMIT_CLOSE_CODE", "4408"))

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default",
    },
    "throttles": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
    },
}

# Application definition

INSTALLED_APPS = [
    'daphne',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "pgvector.django",
    'accounts_supabase',
    'chat',
    'mutes',
    'reminders',
    'drafts',
    'rooms',
    'events',
    'core',
    'state',
    'polls',
    'chat_addons',
]

# REST framework configuration
REST_FRAMEWORK = {
     "DEFAULT_AUTHENTICATION_CLASSES": (
         "accounts_supabase.authentication.DevTokenOrJWTAuthentication",
         #"jatte.auth.supabase.SupabaseJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "message-burst": MESSAGE_BURST_RATE,
        "message-sustained": MESSAGE_SUSTAINED_RATE,
        "reaction-burst": REACTION_BURST_RATE,
        "reaction-sustained": REACTION_SUSTAINED_RATE,
    },
}


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.AllowAny',
#     ),
# }

# Use Supabase signing key for JWT tokens so they work with existing
# `SupabaseJWTAuthentication` used throughout the project.
SIMPLE_JWT = {
    'SIGNING_KEY': SUPABASE_JWT_SECRET,
    'ALGORITHM': 'HS256',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Keep Django's automatic slash-appending behaviour so the React kit
# can consistently call API endpoints with trailing slashes.
APPEND_SLASH = True

ROOT_URLCONF = 'jatte.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jatte.wsgi.application'
ASGI_APPLICATION = 'jatte.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     "default": dj_database_url.parse(
#         os.environ["DATABASE_URL"],
#         conn_max_age=600,
#         ssl_require=True,
#     )
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'postgres',
#         'USER': 'postgres.fzjjnflfsruvjcdpbyfh',
#         'PASSWORD': '***REMOVED***',
#         'HOST': 'aws-0-us-east-1.pooler.supabase.com',
#         'PORT': '5432',
#         'OPTIONS': {
#             'sslmode': 'require',  # Supabase typically requires SSL.
#         },        
#     }
# }
DATABASES = {
    "default": dj_database_url.parse(
        os.environ["DATABASE_URL"],
        conn_max_age=0,
        ssl_require=True,  # ensures sslmode=require in OPTIONS
    )
}


# Allow explicit override from SUPABASE_JWKS_URL env; otherwise use the URL
# derived from NEXT_PUBLIC_SUPABASE_URL near the top of this file.
_env_jwks = os.environ.get("SUPABASE_JWKS_URL")
if _env_jwks:
    SUPABASE_JWKS_URL = _env_jwks


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = _split_env(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000",
)
CORS_ALLOW_CREDENTIALS = False
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        }
    },
    "loggers": {
        "chat": {
            "handlers": ["console"],
            "level": os.environ.get("CHAT_LOG_LEVEL", "INFO"),
            "propagate": True,
        }
    },
}
