# Generated by Django 4.2.1 on 2025-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_supabase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
