from __future__ import annotations

import logging
from dataclasses import dataclass

from django.conf import settings
from django.core.cache import cache
from django.utils import timezone

from .consent import is_opted_out
from ..tasks import sms_autoreply_task

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SmsAutoreplyDecision:
    allowed: bool
    reason: str


def _setting(name: str, default=None):
    return getattr(settings, name, default)


def _is_enabled() -> bool:
    # Back-compat: support both SMS_AUTOREPLY_* and SMS_IRIS_AUTOREPLY_*.
    return bool(_setting("SMS_AUTOREPLY_ENABLED", _setting("SMS_IRIS_AUTOREPLY_ENABLED", False)))


def _allowlist() -> set[str]:
    raw = _setting("SMS_AUTOREPLY_ALLOWLIST", _setting("SMS_IRIS_AUTOREPLY_ALLOWLIST", []) or []) or []
    return set(raw)


def _max_per_hour() -> int:
    raw = _setting("SMS_AUTOREPLY_MAX_PER_HOUR", _setting("SMS_IRIS_AUTOREPLY_MAX_PER_HOUR", 0) or 0) or 0
    try:
        return int(raw)
    except Exception:
        return 0


def _rate_limit_key(sender_e164: str) -> str:
    bucket = timezone.now().strftime("%Y%m%d%H")
    return f"sms_autoreply:{sender_e164}:hour:{bucket}"


def maybe_enqueue_sms_autoreply(*, room, triggering_message, sender_e164: str | None) -> SmsAutoreplyDecision:
    """Decide whether to enqueue an SMS auto-reply for an incoming SMS message.

    NOTE: This service is intentionally (room, triggering_message)-based so it can
    enqueue the Celery task with durable identifiers (room_id + triggering_message_id).
    """
    # 1) Feature flag first (fast exit, avoids DB work when disabled)
    if not _is_enabled():
        return SmsAutoreplyDecision(False, "disabled")

    # 2) Sender allowlist
    allowlist = _allowlist()
    if sender_e164 and allowlist and sender_e164 not in allowlist:
        logger.info(
            "sms.autoreply.skipped",
            extra={"reason": "not_allowlisted", "sender_e164": sender_e164},
        )
        return SmsAutoreplyDecision(False, "not_allowlisted")

    # 3) Opt-out consent
    if sender_e164 and is_opted_out(sender_e164):
        logger.info(
            "sms.autoreply.skipped",
            extra={"reason": "opted_out", "sender_e164": sender_e164},
        )
        return SmsAutoreplyDecision(False, "opted_out")

    # 4) Ignore if this message was generated by our own auto-reply
    custom_data = getattr(triggering_message, "custom_data", {}) or {}
    if isinstance(custom_data, dict) and custom_data.get("source") == "sms_autoreply":
        return SmsAutoreplyDecision(False, "autoreply_message")

    # 5) Empty message guard
    text = (getattr(triggering_message, "body", None) or "").strip()
    if not text:
        return SmsAutoreplyDecision(False, "empty")

    # 6) Rate limit (per sender per hour)
    max_per_hour = _max_per_hour()
    if sender_e164 and max_per_hour > 0:
        key = _rate_limit_key(sender_e164)
        try:
            count = cache.incr(key)
        except ValueError:
            cache.set(key, 1, timeout=60 * 60)
            count = 1

        if count > max_per_hour:
            logger.info(
                "sms.autoreply.skipped",
                extra={"reason": "rate_limited", "sender_e164": sender_e164, "count": count},
            )
            return SmsAutoreplyDecision(False, "rate_limited")

    # 7) Enqueue task using durable identifiers
    sms_autoreply_task.delay(
        room_id=str(room.id),
        triggering_message_id=str(triggering_message.id),
        sender_e164=sender_e164,
    )
    return SmsAutoreplyDecision(True, "enqueued")


__all__ = ["SmsAutoreplyDecision", "maybe_enqueue_sms_autoreply"]
